import path from 'node:path';
import Fastify, { type FastifyInstance, type FastifyReply, type FastifyRequest } from 'fastify';
import openapiGlue from 'fastify-openapi-glue';
import type { AwilixContainer } from 'awilix';
import type { Cradle } from '../container';
import { buildPaymentApi } from '../../payments/adapter/http/incoming/PaymentApiImpl';
import { stubHandlers } from '#generated/payments/adapter/http/incoming/handler-stubs';
import { AccountNotFoundError, DomainError } from '../../payments/domain/Errors';
import { registerBearerAuth } from './security';

const SPEC_PATH = path.resolve(process.cwd(), 'openapi/openapi.yaml');

function problem(status: number, title: string, detail: string) {
  return { type: 'about:blank', title, status, detail };
}

export async function buildServer(container: AwilixContainer<Cradle>): Promise<FastifyInstance> {
  const app = Fastify({
    logger: true, // Fastify bundles pino for structured logs.
    // The contract is OpenAPI 3.0, which carries keywords ajv's JSON-Schema strict
    // mode rejects (`example`, `nullable`). Relax strict mode so glue can build the
    // route validators; ignored keywords are annotations only (nullable fields here
    // are response-side). Without this, boot throws FST_ERR_SCH_VALIDATION_BUILD.
    ajv: { customOptions: { strict: false } },
  });

  const service = {
    // Stubs first: every operationId in the contract resolves to a 501 by default,
    // so a newly-added contract operation boots and returns a clean 501 until its
    // real handler (spread below) overrides the stub. Regenerated by `pnpm codegen:openapi`.
    ...stubHandlers,
    ...buildPaymentApi(container),
    async healthCheck(_request: FastifyRequest, reply: FastifyReply): Promise<void> {
      await reply.code(200).send({ status: 'ok' });
    },
  };

  // Enforce the contract's `security` (global `bearerAuth`) at onRequest — before
  // schema validation — so unauthenticated calls get 401, not 400. See security.ts / ADR-0004.
  registerBearerAuth(app);

  await app.register(openapiGlue, {
    specification: SPEC_PATH,
    service,
    prefix: '/api/v1',
  });

  app.setErrorHandler((err, request, reply) => {
    if (err instanceof AccountNotFoundError) {
      return reply.code(404).type('application/problem+json').send(problem(404, 'Account not found', err.message));
    }
    if (err instanceof DomainError) {
      return reply.code(422).type('application/problem+json').send(problem(422, 'Domain rule violated', err.message));
    }
    // fastify-openapi-glue throws a SecurityError (statusCode 401) when no security
    // scheme authenticates the request; surface it as problem+json (ADR-0004).
    if ((err as { statusCode?: number }).statusCode === 401) {
      return reply.code(401).type('application/problem+json').send(problem(401, 'Unauthorized', (err as Error).message));
    }
    if ((err as { validation?: unknown }).validation) {
      return reply.code(400).type('application/problem+json').send(problem(400, 'Invalid request', (err as Error).message));
    }
    request.log.error(err);
    return reply.code(500).type('application/problem+json').send(problem(500, 'Internal Server Error', 'Unexpected error'));
  });

  return app;
}
